- name: configure mysql server
  hosts: mysql
  become: yes # use sudo to run tasks as root
  tasks:
    - name: Install MySQL Server
      ansible.builtin.package:
        name: mysql-server
        state: installed

    - name: Ensure MySQL service is running and enabled
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
